pgsql:
  jdbc:
    url:  jdbc:postgresql://172.30.162.106:5432/postgres
    username: postgres
    password: postgres
jpa:
  show-sql: true
  generate-ddl: false
  hibernate-ddl-auto: create # Hibernate ddl auto (create, create-drop, validate, update)
